from lib import domain, example, formula, heading, numworks, table, text, tip, topic, warning

machten = topic(
    "b1-machten", "Machten en wortels",
    "Rekenregels voor machten en wortels (bijlage 4, D1–D6 en B).",
    "B1.1", ["machten", "exponent", "wortel", "rekenregels", "gebroken exponent", "negatieve exponent"],
    [
        text("Deze regels staan **niet** op de formulelijst. Ze gelden voor $a > 0$ en $b > 0$."),
        formula("mac-prod", r"a^p \cdot a^q = a^{p+q}", "a tot de p keer a tot de q is a tot de p plus q",
                caption="Vermenigvuldigen: exponenten optellen", question=r"$a^p \cdot a^q$ = ?"),
        formula("mac-quot", r"\frac{a^p}{a^q} = a^{p-q}", "a tot de p gedeeld door a tot de q is a tot de p min q",
                caption="Delen: exponenten aftrekken", question=r"$\frac{a^p}{a^q}$ = ?"),
        formula("mac-macht", r"\left(a^p\right)^q = a^{p \cdot q}", "a tot de p, alles tot de q, is a tot de p keer q",
                caption="Macht van een macht: vermenigvuldigen", question=r"$\left(a^p\right)^q$ = ?"),
        formula("mac-product", r"(a \cdot b)^p = a^p \cdot b^p", "a keer b tot de p is a tot de p keer b tot de p",
                caption="Macht van een product", question=r"$(a \cdot b)^p$ = ?"),
        formula("mac-neg", r"a^{-p} = \frac{1}{a^p}", "a tot de min p is 1 gedeeld door a tot de p",
                caption="Negatieve exponent", question=r"$a^{-p}$ = ?"),
        formula("mac-wortel", r"a^{\frac{1}{p}} = \sqrt[p]{a}", "a tot de 1 p-de is de p-de machtswortel van a",
                caption=r"Gebroken exponent ($p$ positief en geheel)", question=r"$a^{\frac{1}{p}}$ = ?"),
        formula("mac-nul", r"a^0 = 1 \qquad a^1 = a", "a tot de nul is 1, a tot de 1 is a", caption="Speciale exponenten"),
        heading("Wortels"),
        formula("wor-prod", r"\sqrt{A} \cdot \sqrt{B} = \sqrt{A \cdot B}", "wortel A keer wortel B is wortel A keer B",
                caption="Wortels vermenigvuldigen"),
        formula("wor-quot", r"\frac{\sqrt{A}}{\sqrt{B}} = \sqrt{\frac{A}{B}}", "wortel A gedeeld door wortel B is wortel van A gedeeld door B",
                caption="Wortels delen"),
        formula("wor-macht", r"\sqrt{x} = x^{0,5} \qquad \frac{1}{\sqrt{x}} = x^{-0,5}", "wortel x is x tot de 0,5, 1 gedeeld door wortel x is x tot de min 0,5",
                caption="Wortel als macht (handig bij differentiëren)", question=r"Schrijf $\frac{1}{\sqrt{x}}$ als macht van $x$"),
        example("Voorbeeld", r"Schrijf $\frac{8x^3}{(2x)^2}$ zo eenvoudig mogelijk.", [
            (r"Werk eerst de macht van het product uit: $(2x)^2 = 2^2 \cdot x^2 = 4x^2$.", None),
            ("Deel getallen en machten apart.", r"\frac{8x^3}{4x^2} = \frac{8}{4} \cdot x^{3-2}"),
            ("Dus:", r"\frac{8x^3}{(2x)^2} = 2x"),
        ]),
        warning(r"$(a + b)^2 \neq a^2 + b^2$ en $\sqrt{a + b} \neq \sqrt{a} + \sqrt{b}$. De regels gelden alleen voor **vermenigvuldigen** en **delen**."),
    ],
)

breuken = topic(
    "b1-breuken", "Breuken en haakjes",
    "Rekenen met breuken en haakjes wegwerken (bijlage 4, A en C).",
    "B1.3", ["breuken", "haakjes", "noemer", "gelijknamig", "haakjes wegwerken", "bijzondere producten"],
    [
        formula("br-optellen", r"\frac{A}{B} + \frac{C}{D} = \frac{AD + BC}{BD}", "A over B plus C over D is A D plus B C over B D",
                caption="Optellen: eerst gelijknamig maken"),
        formula("br-splitsen", r"\frac{A + B}{C} = \frac{A}{C} + \frac{B}{C}", "A plus B over C is A over C plus B over C",
                caption="Breuk splitsen (alleen bij de teller!)"),
        formula("br-keer-getal", r"A \cdot \frac{B}{C} = \frac{A \cdot B}{C}", "A keer B over C is A B over C",
                caption="Breuk keer een getal"),
        formula("br-keer", r"\frac{A}{B} \cdot \frac{C}{D} = \frac{A \cdot C}{B \cdot D}", "A over B keer C over D is A C over B D",
                caption="Breuken vermenigvuldigen"),
        formula("br-delen", r"\frac{A}{\frac{B}{C}} = \frac{A \cdot C}{B}", "A gedeeld door B over C is A C over B",
                caption="Delen door een breuk: vermenigvuldigen met het omgekeerde"),
        warning(r"$\frac{A}{B + C} \neq \frac{A}{B} + \frac{A}{C}$. Splitsen mag alleen als de **teller** een som is."),
        heading("Haakjes wegwerken"),
        formula("hk-dubbel", r"(A + B)(C + D) = AC + AD + BC + BD", "A plus B keer C plus D is A C plus A D plus B C plus B D",
                caption="Dubbele haakjes: iedere term met iedere term"),
        formula("hk-xab", r"(x + a)(x + b) = x^2 + (a + b)x + ab", "x plus a keer x plus b is x kwadraat plus a plus b keer x plus a b",
                caption="Bijzonder product"),
        formula("hk-kwadraat", r"(A + B)^2 = A^2 + 2AB + B^2", "A plus B in het kwadraat is A kwadraat plus 2 A B plus B kwadraat",
                badge="extra", caption="Kwadraat van een som"),
        text("Bij wiskunde A hoef je alleen haakjes **weg te werken**; ontbinden in factoren wordt niet gevraagd."),
        example("Voorbeeld", r"Werk de haakjes weg: $(2x - 3)(x + 4)$.", [
            ("Vermenigvuldig iedere term met iedere term.", r"2x \cdot x + 2x \cdot 4 - 3 \cdot x - 3 \cdot 4"),
            ("Tel gelijksoortige termen op.", r"2x^2 + 8x - 3x - 12 = 2x^2 + 5x - 12"),
        ]),
    ],
)

procenten = topic(
    "b1-procenten", "Procenten, verhoudingen en groeifactor",
    "Absoluut en relatief, procentuele verandering en groeifactoren.",
    "B1.2", ["procent", "percentage", "groeifactor", "relatief", "absoluut", "verhouding", "procentpunt", "toename"],
    [
        text("**Absoluut** is het aantal zelf (bijv. 300 leerlingen). **Relatief** is een deel van het geheel (bijv. 25 % van de leerlingen)."),
        formula("pct-verandering", r"\text{procentuele verandering} = \frac{\text{nieuw} - \text{oud}}{\text{oud}} \cdot 100\pct",
                "procentuele verandering is nieuw min oud gedeeld door oud, keer 100 procent",
                caption="Procentuele toename of afname", question="Hoe bereken je de procentuele verandering?"),
        formula("pct-groeifactor", r"g = 1 + \frac{p}{100}", "groeifactor g is 1 plus p gedeeld door 100",
                caption=r"Groeifactor bij een toename van $p\pct$", question=r"Groeifactor bij een toename van $p\pct$?"),
        table(["verandering", "groeifactor"], [
            [r"$+8\pct$", "$1,08$"],
            [r"$-8\pct$", "$0,92$"],
            [r"$+150\pct$", "$2,5$"],
            [r"$-100\pct$", "$0$"],
        ], caption="Voorbeelden"),
        tip(r"Opeenvolgende veranderingen: **vermenigvuldig** de groeifactoren. $+10\pct$ en daarna $-10\pct$ geeft $1,1 \cdot 0,9 = 0,99$, dus $-1\pct$."),
        text(r"**Procentpunt**: het verschil tussen twee percentages. Van 20 % naar 25 % is een stijging van **5 procentpunt**, en tegelijk een **relatieve** stijging van 25 % (want $\frac{25 - 20}{20} = 0,25$)."),
        example("Voorbeeld", r"Een fiets kost na $15\pct$ korting € 425. Wat was de oorspronkelijke prijs?", [
            (r"Korting van $15\pct$ betekent groeifactor $0,85$.", r"0,85 \cdot \text{oud} = 425"),
            ("Deel door de groeifactor.", r"\text{oud} = \frac{425}{0,85} = 500"),
            ("De fiets kostte € 500.", None),
        ]),
    ],
)

eenheden = topic(
    "b1-eenheden", "Grootheden en eenheden",
    "Samengestelde grootheden en eenheden omrekenen.",
    "B1.6", ["eenheden", "omrekenen", "grootheden", "snelheid", "dichtheid", "km/h", "m/s", "liter"],
    [
        table(["van", "naar", "reken"], [
            ["km/h", "m/s", r"$: 3,6$"],
            ["m/s", "km/h", r"$\cdot 3,6$"],
            ["m²", "cm²", r"$\cdot 10\,000$"],
            ["m³", "dm³ = liter", r"$\cdot 1000$"],
            ["uur", "minuten", r"$\cdot 60$"],
            ["dag", "uur", r"$\cdot 24$"],
        ], caption="Veelgebruikte omrekeningen"),
        formula("eh-snelheid", r"\text{snelheid} = \frac{\text{afstand}}{\text{tijd}}", "snelheid is afstand gedeeld door tijd",
                caption="Samengestelde grootheid"),
        tip("Reken eenheden mee als een breuk: $\\frac{\\text{km}}{\\text{h}} = \\frac{1000 \\text{ m}}{3600 \\text{ s}}$. Zo zie je meteen of je moet vermenigvuldigen of delen."),
        tip("Kijk bij formules uit de context altijd in welke eenheid de variabelen staan (bijv. $t$ in jaren vanaf 2020)."),
    ],
)

herleiden = topic(
    "b1-herleiden", "Formules herleiden",
    "Een formule omwerken naar de gevraagde vorm, zonder GR (bijlage 4, G en H).",
    "C2.2", ["herleiden", "omwerken", "formule", "vrijmaken", "vergelijking", "balansmethode"],
    [
        text("**Herleiden** betekent: stap voor stap herschrijven tot de gevraagde vorm, **zonder** opties van de GR. Laat iedere stap zien."),
        formula("hl-lineair", r"ax + b = c \Leftrightarrow x = \frac{c - b}{a}", "a x plus b is c, dus x is c min b gedeeld door a",
                caption="Eerstegraads"),
        formula("hl-breuk", r"\frac{A}{B} = C \Leftrightarrow A = B \cdot C", "A over B is C, dus A is B keer C",
                caption="Breuk wegwerken"),
        formula("hl-kruislings", r"\frac{A}{B} = \frac{C}{D} \Leftrightarrow A \cdot D = B \cdot C", "A over B is C over D, dus A D is B C",
                caption="Kruislings vermenigvuldigen"),
        formula("hl-wortel", r"\sqrt{A} = B \Leftrightarrow A = B^2", "wortel A is B, dus A is B kwadraat",
                caption=r"Wortel wegwerken ($B \geq 0$)"),
        formula("hl-macht", r"x^n = c \Leftrightarrow x = c^{\frac{1}{n}}", "x tot de n is c, dus x is c tot de 1 n-de",
                caption=r"Macht wegwerken ($x > 0$)", question=r"Maak $x$ vrij: $x^n = c$ (met $x > 0$)"),
        formula("hl-exp", r"g^x = a \Leftrightarrow x = \glog{g}(a)", "g tot de x is a, dus x is g-log a",
                caption="Exponent vrijmaken", question=r"Maak $x$ vrij: $g^x = a$"),
        formula("hl-log", r"\glog{g}(x) = b \Leftrightarrow x = g^b", "g-log x is b, dus x is g tot de b",
                caption="Logaritme wegwerken", question=r"Maak $x$ vrij: $\glog{g}(x) = b$"),
        formula("hl-e", r"e^x = a \Leftrightarrow x = \ln(a)", "e tot de x is a, dus x is ln a",
                caption=r"Met $e$", question=r"Maak $x$ vrij: $e^x = a$"),
        formula("hl-ln", r"\ln(x) = b \Leftrightarrow x = e^b", "ln x is b, dus x is e tot de b",
                caption="Met ln", question=r"Maak $x$ vrij: $\ln(x) = b$"),
        example("Voorbeeld", r"Gegeven $N = 20 \cdot 1,5^t$. Herleid tot een formule van de vorm $t = \ldots$", [
            ("Deel beide kanten door 20.", r"1,5^t = \frac{N}{20}"),
            ("Gebruik de definitie van de logaritme.", r"t = \glog{1,5}\left(\frac{N}{20}\right)"),
        ]),
        example("Voorbeeld", r"Herleid $y = \frac{12}{x + 3}$ tot $x = \ldots$", [
            (r"Vermenigvuldig met $x + 3$.", r"y(x + 3) = 12"),
            (r"Deel door $y$.", r"x + 3 = \frac{12}{y}"),
            ("Trek 3 af.", r"x = \frac{12}{y} - 3"),
        ]),
    ],
)

tellen = topic(
    "b2-tellen", "Telproblemen",
    "Boomdiagram, wegendiagram, rooster, permutaties en combinaties.",
    "B2.1", ["tellen", "combinatoriek", "permutaties", "combinaties", "faculteit", "boomdiagram", "wegendiagram", "rooster", "volgorde"],
    [
        text("Schematiseer eerst: **boomdiagram**, **wegendiagram** of **rooster**. Kies daarna de goede telregel."),
        formula("tel-product", r"\text{aantal} = n_1 \cdot n_2 \cdot \ldots \cdot n_k", "aantal is n 1 keer n 2 keer enzovoort",
                caption="Vermenigvuldigingsregel: keuzes na elkaar", question="Hoe tel je keuzes die na elkaar gemaakt worden?"),
        formula("tel-herhaling", r"n^k", "n tot de k",
                caption=r"Volgorde belangrijk, herhaling toegestaan ($k$ keer kiezen uit $n$)",
                question=r"Aantal mogelijkheden: $k$ keer kiezen uit $n$, **met** herhaling, volgorde belangrijk?"),
        formula("tel-faculteit", r"n! = n \cdot (n - 1) \cdot \ldots \cdot 2 \cdot 1", "n faculteit is n keer n min 1 keer enzovoort tot 1",
                caption=r"Alle $n$ dingen op een rij zetten", question=r"Op hoeveel manieren zet je $n$ verschillende dingen op een rij?"),
        formula("tel-permutaties", r"\frac{n!}{(n - k)!} = n \cdot (n - 1) \cdot \ldots \cdot (n - k + 1)", "n faculteit gedeeld door n min k faculteit",
                caption=r"Permutaties: $k$ uit $n$, volgorde **wel** belangrijk",
                question=r"Aantal permutaties van $k$ uit $n$ (volgorde belangrijk, zonder herhaling)?"),
        formula("tel-combinaties", r"\binom{n}{k} = \frac{n!}{k! \cdot (n - k)!}", "n boven k is n faculteit gedeeld door k faculteit keer n min k faculteit",
                caption=r"Combinaties: $k$ uit $n$, volgorde **niet** belangrijk",
                question=r"Aantal combinaties van $k$ uit $n$ (volgorde niet belangrijk)?"),
        table(["", "volgorde belangrijk", "volgorde niet belangrijk"], [
            ["met herhaling", "$n^k$", "(komt niet voor)"],
            ["zonder herhaling", r"$\frac{n!}{(n-k)!}$", r"$\binom{n}{k}$"],
        ], caption="Welke telregel?"),
        heading("Rooster en rangschikken"),
        formula("tel-rooster", r"\binom{a + b}{a}", "a plus b boven a",
                caption=r"Kortste routes in een rooster: $a$ stappen naar rechts en $b$ omhoog",
                question=r"Aantal kortste routes in een rooster met $a$ stappen rechts en $b$ stappen omhoog?"),
        text(r"Dezelfde formule telt rijtjes met $a$ gelijke en $b$ andere gelijke dingen, bijv. het aantal rijtjes van 5 letters met 2 keer A en 3 keer B: $\binom{5}{2} = 10$."),
        text("**Wegendiagram**: vermenigvuldig langs één route, tel verschillende routes op."),
        example("Voorbeeld", "Uit een klas van 25 leerlingen worden een voorzitter, een secretaris en een penningmeester gekozen. Hoeveel mogelijkheden zijn er? En als er alleen een commissie van 3 wordt gekozen?", [
            ("Functies zijn verschillend: volgorde is belangrijk. Permutaties:", r"25 \cdot 24 \cdot 23 = 13\,800"),
            ("Commissie zonder functies: volgorde niet belangrijk. Combinaties:", r"\binom{25}{3} = 2300"),
        ]),
        numworks("Rekenen", [
            "Toolbox-toets → **Kansrekenen** → **Combinatoriek**.",
            "Kies **Combinatie** voor `binomial(n,k)`, **Permutatie** voor `permute(n,k)`.",
            "Faculteit: `n!` staat in hetzelfde menu.",
        ], note="Voorbeeld: binomial(25,3) = 2300 en permute(25,3) = 13800."),
    ],
)

DOMAIN = domain("B", "B", "Algebra en tellen", "plus.forwardslash.minus", "blue",
                [machten, breuken, procenten, eenheden, herleiden, tellen])
