/** Mirrors Spiekbrief/Content/Models.swift. The JSON is generated by tools/content/build.py. */

/** How the student should treat a formula at the exam. */
export type Badge = 'formulelijst' | 'paraat' | 'se' | 'extra'

export const badgeLabel: Record<Badge, string> = {
  formulelijst: 'Op formulelijst',
  paraat: 'Paraat kennen',
  se: 'SE',
  extra: 'Handig, niet vereist',
}

export interface Formula {
  id: string
  latex: string
  /** Dutch text read by screen readers. */
  spoken: string
  badge: Badge
  caption?: string
  /** Condition shown under the formula, e.g. "$g > 0$, $g \neq 1$". */
  condition?: string
  /** Flashcard question; formulas with a question become flashcards. */
  question?: string
}

export interface ExampleStep {
  text: string
  latex?: string
}

export interface Example {
  title: string
  /** The question, shown before the steps are revealed. */
  problem: string
  steps: ExampleStep[]
}

export interface NumWorksTip {
  /** App name as shown on the calculator, e.g. "Functies", "Kansrekenen". */
  app: string
  steps: string[]
  note?: string
}

export interface TableData {
  caption?: string
  headers: string[]
  rows: string[][]
}

/**
 * Swift's `Block` enum encodes a `type` discriminator with a flattened payload beside it,
 * which is exactly a TypeScript discriminated union.
 */
export type Block =
  | { type: 'text'; text: string }
  | { type: 'heading'; text: string }
  | { type: 'tip'; text: string }
  | { type: 'warning'; text: string }
  | { type: 'graph'; graph: string }
  | ({ type: 'formula' } & Formula)
  | ({ type: 'example' } & Example)
  | ({ type: 'numworks' } & NumWorksTip)
  | ({ type: 'table' } & TableData)

export interface Topic {
  id: string
  title: string
  summary: string
  /** Reference to the syllabus section, e.g. "C2.3" (subdomein + vaardigheid). */
  syllabusRef: string
  keywords?: string[]
  blocks: Block[]
}

export interface Domain {
  id: string
  code: string
  title: string
  /** SF Symbol name on iOS; mapped to a Lucide icon on the web, see src/app/icons.ts. */
  symbol: string
  /** Name of a system color, see domainTint in src/app/icons.ts. */
  color: string
  /** True for school-exam-only content (domain E). */
  schoolExamOnly?: boolean
  topics: Topic[]
}

/** A flashcard, derived from a formula that has a `question`. */
export interface Flashcard {
  id: string
  question: string
  formula: Formula
  topicId: string
  domainId: string
}

/** All formulas of a topic, in document order, with their stable ids. */
export function topicFormulas(topic: Topic): Formula[] {
  return topic.blocks.filter((b): b is { type: 'formula' } & Formula => b.type === 'formula')
}
