import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { fileURLToPath, URL } from 'node:url'

// The content JSON is generated by tools/content/build.py and bundled by the iOS app.
// We import it straight from there so there is no copy to keep in sync.
const contentDir = fileURLToPath(new URL('../Spiekbrief/Resources/Content', import.meta.url))

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icon-192.png', 'icon-512.png', 'apple-touch-icon.png'],
      manifest: {
        name: 'Spiekbrief Wiskunde A',
        short_name: 'Spiekbrief',
        description: 'Spiekbrief voor het centraal examen wiskunde A vwo.',
        lang: 'nl',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#f2f2f7',
        theme_color: '#1d66c7',
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Everything ships in the precache: the app must work with no signal at all.
        globPatterns: ['**/*.{js,css,html,woff2,png,svg}'],
        // woff2 only: every browser that can run this app supports it, and precaching
        // the woff and ttf copies of the KaTeX fonts would triple the offline payload.
        globIgnores: ['**/*.{woff,ttf}'],
        navigateFallback: '/index.html',
      },
    }),
  ],
  resolve: {
    alias: {
      '@content': contentDir,
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    fs: { allow: ['..'] },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
  },
})
